Country configuration
wearesho-team/google-autocomplete pull request #12
Opened 2018-09-10 12:56 UTC by KartaviK

2018-09-24 09:14 UTC, Horat1us commented
#11

2018-09-24 09:18 UTC, Horat1us requested changes

2018-09-24 09:18 UTC, Horat1us commented on src/Service.php
> +                static::COMPONENTS => static::COUNTRY . $this->config->getCountry(),
config->getCountry() should be converted to lower case using mb_strtolower because of missing validation in configuration classes

2018-09-26 10:12 UTC, sashabeton approved these changes

2018-09-26 10:18 UTC, Horat1us requested changes
Missing test that ensures that mb_strtoupper applied to country code

2018-09-26 13:29 UTC, Horat1us approved these changes

2018-09-26 13:29 UTC, merged